<?php
/**
 * Copyright © Magenx. All rights reserved.
 */
declare(strict_types=1);

namespace Magenx\AiMcp\Test\Unit\Model\Tool\Media;

use Magenx\AiMcp\Model\Tool\Media\AddProductMedia;
use Magenx\AiMcp\Model\Tool\Media\Base64Payload;
use Magenx\AiMcp\Model\Tool\Media\MediaEntryProjector;
use Magenx\AiMcp\Test\Unit\GeneratedFactory;
use Magento\Catalog\Api\Data\ProductAttributeMediaGalleryEntryInterface as Entry;
use Magento\Catalog\Api\Data\ProductAttributeMediaGalleryEntryInterfaceFactory;
use Magento\Catalog\Api\ProductAttributeMediaGalleryManagementInterface;
use Magento\Framework\Api\Data\ImageContentInterface;
use Magento\Framework\Api\Data\ImageContentInterfaceFactory;
use Magento\Framework\Exception\LocalizedException;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

/**
 * The image payload check in front of Magento's gallery upload.
 *
 * Magento validates the image too, but only after attempting the upload, and
 * it reports the result as a generic save failure. What is pinned here is that
 * a bad payload is refused *before* anything is written, with a message naming
 * the actual problem.
 *
 * @see AddProductMedia
 */
class AddProductMediaTest extends TestCase
{
    private ProductAttributeMediaGalleryManagementInterface&MockObject $mediaGallery;

    private AddProductMedia $tool;

    /**
     * @return void
     */
    protected function setUp(): void
    {
        // Both factories are generated by Magento rather than shipped.
        GeneratedFactory::ensure(ProductAttributeMediaGalleryEntryInterfaceFactory::class);
        GeneratedFactory::ensure(ImageContentInterfaceFactory::class);

        $this->mediaGallery = $this->createMock(ProductAttributeMediaGalleryManagementInterface::class);

        $entryFactory = $this->createMock(ProductAttributeMediaGalleryEntryInterfaceFactory::class);
        $entryFactory->method('create')->willReturnCallback(
            fn (): Entry => $this->createMock(Entry::class)
        );

        $contentFactory = $this->createMock(ImageContentInterfaceFactory::class);
        $contentFactory->method('create')->willReturnCallback(
            fn (): ImageContentInterface => $this->createMock(ImageContentInterface::class)
        );

        $this->tool = new AddProductMedia(
            $this->mediaGallery,
            $entryFactory,
            $contentFactory,
            new MediaEntryProjector(),
            new Base64Payload()
        );
    }

    /**
     * @param string $data
     * @param string $mimeType
     * @param string $expectedMessage
     * @return void
     */
    #[DataProvider('badPayloadProvider')]
    public function testABadPayloadIsRefusedBeforeAnythingIsUploaded(
        string $data,
        string $mimeType,
        string $expectedMessage
    ): void {
        // The point of the check: Magento is never reached.
        $this->mediaGallery->expects($this->never())->method('create');

        $this->expectException(LocalizedException::class);
        $this->expectExceptionMessage($expectedMessage);

        $this->tool->execute([
            'sku' => 'SKU-1',
            'file_name' => 'shirt.jpg',
            'mime_type' => $mimeType,
            'base64_encoded_data' => $data,
        ]);
    }

    /**
     * @return array<string, array{0: string, 1: string, 2: string}>
     */
    public static function badPayloadProvider(): array
    {
        return [
            'not base64 at all' => [
                '!!!! not base64 !!!!',
                'image/png',
                'is not valid base64',
            ],
            'base64 of something that is not an image' => [
                base64_encode('this is a text file, not a picture'),
                'image/png',
                'does not decode to an image Magento can read',
            ],
            // The commonest real mistake: right bytes, wrong declared type.
            'mime type disagrees with the bytes' => [
                self::onePixelPng(),
                'image/jpeg',
                'Pass the type that matches the image.',
            ],
        ];
    }

    /**
     * @return void
     */
    public function testAnUnsupportedMimeTypeIsRefused(): void
    {
        $this->mediaGallery->expects($this->never())->method('create');

        $this->expectException(LocalizedException::class);
        $this->expectExceptionMessage('The "mime_type" argument must be one of');

        $this->tool->execute([
            'sku' => 'SKU-1',
            'file_name' => 'shirt.svg',
            'mime_type' => 'image/svg+xml',
            'base64_encoded_data' => self::onePixelPng(),
        ]);
    }

    /**
     * @return void
     */
    public function testAnUnknownRoleIsRefused(): void
    {
        $this->mediaGallery->expects($this->never())->method('create');

        $this->expectException(LocalizedException::class);
        $this->expectExceptionMessage('Every entry in "types" must be one of');

        $this->tool->execute([
            'sku' => 'SKU-1',
            'file_name' => 'shirt.png',
            'mime_type' => 'image/png',
            'base64_encoded_data' => self::onePixelPng(),
            'types' => ['hero_image'],
        ]);
    }

    /**
     * @return void
     */
    public function testAValidPayloadReachesMagento(): void
    {
        $this->mediaGallery->expects($this->once())
            ->method('create')
            ->with('SKU-1', $this->isInstanceOf(Entry::class))
            ->willReturn(7);
        $this->mediaGallery->expects($this->once())
            ->method('get')
            ->with('SKU-1', 7)
            ->willReturn($this->createMock(Entry::class));

        $result = $this->tool->execute([
            'sku' => 'SKU-1',
            'file_name' => 'shirt.png',
            'mime_type' => 'image/png',
            'base64_encoded_data' => self::onePixelPng(),
            'types' => ['image', 'small_image'],
        ]);

        $this->assertTrue($result['created']);
        $this->assertSame('SKU-1', $result['sku']);
    }

    /**
     * A real 1x1 PNG, so the type sniffing under test has something genuine to
     * read rather than a hand-written header.
     *
     * @return string
     */
    private static function onePixelPng(): string
    {
        return 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAC0lEQVR4nGP4z8AAAAMBAQAY3Y2wAAAAAElFTkSuQmCC';
    }
}
